apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-services
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
