nameOverride: demo-api
fullnameOverride: demo-api

image:
  repository: ghcr.io/rodolfo-schiavon/k8s-lab-demo-api
  tag: 5855182c8014aaf5a11fc63ec10c8d93a0ecb443
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.k8s-lab.zerotouch.tec.br
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: demo-api-tls
      hosts:
        - api.k8s-lab.zerotouch.tec.br

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3

env:
  - name: DATABASE_URL
    value: postgresql://demo:k8slab-postgres-change-me@postgres-postgresql.data-services.svc.cluster.local:5432/demodb

nodeSelector:
  node-role: worker-app

hpa:
  enabled: false

pdb:
  enabled: true
  minAvailable: 1
