apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
    platform.layer: data
spec:
  project: default
  source:
    repoURL: https://github.com/rodolfo-schiavon/k8s-kubeadm-lab.git
    targetRevision: main
    path: gitops/apps/postgres
    directory:
      include: "{manifest.yaml,networkpolicy.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: data-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
