apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: k8s-kubeadm-lab
    platform.layer: foundation
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: "3.12.x"
    helm:
      releaseName: metrics-server
      valuesObject:
        args:
          - --kubelet-insecure-tls
        nodeSelector:
          node-role: control-plane
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
